### ISSUE TITLE
Declare Global vars inside the Sandbox, and make them available only there...

### ISSUE THREAD

**Issue by DrOctavius** [Corveda/PHPSandbox#13]
Hi, is it possible to Declare Global vars inside the Sandbox, and make them available only there...? 
I need this because i want to execute a lot of functions using same global vars => but i need to execute them in multithreading environment, so don't  need them to access same var with same memory stack (same pointer), need to separate them without changing the Arhitecture and classes...

**Comment by fieryprophet** [comment]
It's not possible as the sandbox runs within the same global context as the PHP thread itself, so every sandbox running within that thread would have access to the same overall global state (if you allow those sandboxes to access the global state, that is.)
