### ISSUE TITLE
Update nikic/php-parser to latest version

### ISSUE THREAD

**Issue by iskren-dimov** [Corveda/PHPSandbox#18]
Hello,

Is there anything preventing you from using the latest version of nikic/php-parser (v.4)?
We have other dependencies in our projects which require the newer version (at least version 3) and we are having troubles with that.

**Comment by max-gryshin** [comment]
same problem

**Comment by daodao97** [comment]
same problem

**Comment by fieryprophet** [comment]
Resolved in #22
