### ISSUE TITLE
May be need make release

### ISSUE THREAD

**Issue by 4n70w4** [Corveda/PHPSandbox#23]
Hi! Latest release v2.0.1 released this on 20 May 2016

Now there are 11 commits not included in any of the releases.

![image](https://user-images.githubusercontent.com/38257723/100776665-dc4e2b00-3415-11eb-80b6-8eb1066d0299.png)

**Comment by peter279k** [comment]
I also need the new released version 👍.

**Comment by fieryprophet** [comment]
v3.0 is now live.

**Comment by peter279k** [comment]
@fieryprophet, many thanks for this. I appreciate that :).
