### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by Jobians** [Corveda/PHPSandbox#34]
Deprecated: Return type of FunctionParser\Tokenizer::seek($index) should either be compatible with SeekableIterator::seek(int $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 302

Deprecated: Return type of FunctionParser\Tokenizer::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 248

Deprecated: Return type of FunctionParser\Tokenizer::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 256

Deprecated: Return type of FunctionParser\Tokenizer::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 274

Deprecated: Return type of FunctionParser\Tokenizer::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 284

Deprecated: Return type of FunctionParser\Tokenizer::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 292

Deprecated: Return type of FunctionParser\Tokenizer::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 378

Deprecated: Return type of FunctionParser\Tokenizer::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 313

Deprecated: Return type of FunctionParser\Tokenizer::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 324

Deprecated: Return type of FunctionParser\Tokenizer::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 336

Deprecated: Return type of FunctionParser\Tokenizer::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 356

Deprecated: FunctionParser\Tokenizer implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Tokenizer.php on line 15

Deprecated: FunctionParser\Token implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /data/data/com.termux/files/home/php/bota/vendor/jeremeamia/functionparser/src/Token.php on line 21
string(11) "Hello world"

**Comment by peter279k** [comment]
It seems that the issue is about the [jeremeamia/FunctionParser](https://github.com/jeremeamia/FunctionParser) dependency.

**Comment by Jobians** [comment]
> It seems that the issue is about the [jeremeamia/FunctionParser](https://github.com/jeremeamia/FunctionParser) dependency.

How to fix it

**Comment by peter279k** [comment]
It's related to the dependency and it needs to submit issue or PR to the [jeremeamia/FunctionParser](https://github.com/jeremeamia/FunctionParser).

**Comment by Jobians** [comment]
Ok thanks
